// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4fFQdQBgcPnzVEmwBB-kBzSWYydtb0o',
    appId: '1:456536405076:web:399096c4dead0ff29929c1',
    messagingSenderId: '456536405076',
    projectId: 'fluttertest-a3ec1',
    authDomain: 'fluttertest-a3ec1.firebaseapp.com',
    storageBucket: 'fluttertest-a3ec1.appspot.com',
    measurementId: 'G-K2MSJV1BXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdM5VsQ809qwqmfu4E-bCb8ZMIZWbIsQY',
    appId: '1:456536405076:android:41ee3c5bfd03ff209929c1',
    messagingSenderId: '456536405076',
    projectId: 'fluttertest-a3ec1',
    storageBucket: 'fluttertest-a3ec1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfdoYl_S6j43CHuq2LBBb6ZS4RbrbLRdI',
    appId: '1:456536405076:ios:d3947316f8e9ff0e9929c1',
    messagingSenderId: '456536405076',
    projectId: 'fluttertest-a3ec1',
    storageBucket: 'fluttertest-a3ec1.appspot.com',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfdoYl_S6j43CHuq2LBBb6ZS4RbrbLRdI',
    appId: '1:456536405076:ios:b99ee32b5d8ce5e79929c1',
    messagingSenderId: '456536405076',
    projectId: 'fluttertest-a3ec1',
    storageBucket: 'fluttertest-a3ec1.appspot.com',
    iosBundleId: 'com.example.fluttertest.RunnerTests',
  );
}
